[tool.pytest.ini_options]
testpaths = ["tests/unit_tests"]
python_files = "test_*.py"
python_classes = "*TestCase *Test"
python_functions = "test_*"

[tool.ruff]
include = ["pyanaconda/**/*.py", "tests/**/*.py", "scripts/**/*.py"]
extend = "tests/ruff/ruff.toml"

[tool.darker]
formatter = "ruff"
