# Do a build of the rhel-8 branch to RH internal COPR
name: Build current anaconda rhel-8 branch in RHEL COPR
on:
  schedule:
    - cron: 0 2 * * *
  # be able to start this action manually from a actions tab when needed
  workflow_dispatch:

jobs:
  build:
    name: copr-builder
    runs-on: [self-hosted, kstest]
    env:
      CI_CONTAINER: rhinstaller/anaconda-rhel-copr:rhel-8
    steps:
      - name: Clone anaconda repository
        uses: actions/checkout@v2.3.4
        with:
          ref: master
          fetch-depth: 0
          path: anaconda

      - name: Build the build container
        run: |
          sudo podman build --no-cache -t ${{ env.CI_CONTAINER }} anaconda/dockerfile/anaconda-rhel-copr

      - name: Run copr-builder
        run: |
          sudo podman run -i --rm --privileged -v /home/github/copr-rhel-token:/copr-builder/copr-rhel-token:ro,z ${{ env.CI_CONTAINER }} <<EOF
          set -eux
          /copr-builder/copr-builder -v -c /copr-builder/copr-builder-rhel.conf -C /copr-builder/copr-rhel-token
          EOF
