name: validate
on: [push, pull_request_target]
jobs:
  unit-tests:
    # this already is a ci-tasks:rhel-8 container environment
    runs-on: [self-hosted, ci-tasks, rhel-8]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run tests
        id: run-unit-tests
        run: |
          ./autogen.sh
          ./configure
          make
          make ci
        continue-on-error: true

      - name: Upload test and coverage logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            tests/test-suite.log
            tests/pylint/runpylint*.log
            tests/coverage-*.log

      - name: Set job result
        if: ${{ steps.run-unit-tests.outcome == 'failure' }}
        run: |
          cat tests/test-suite.log
          exit 1
