name: validate
on: [push, pull_request_target]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}

      # FIXME: this should only be done if a PR touches dockerfile/ci-tasks, otherwise take the current one from registry
      - name: Build ci-tasks container
        run: CONTAINER_ENGINE=docker make -f Makefile.am ci-tasks-build

      - name: Run tests in ci-tasks container
        id: run-unit-tests
        run: CONTAINER_ENGINE=docker make -f Makefile.am container-ci
        continue-on-error: true

      - name: Upload test and coverage logs
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            tests/test-suite.log
            tests/nosetests.log
            tests/pylint/runpylint*.log
            tests/coverage-*.log

      - name: Set job result
        if: ${{ steps.run-unit-tests.outcome == 'failure' }}
        run: |
          cat tests/test-suite.log
          exit 1

  rpm-tests:
    runs-on: ubuntu-latest
    # start from a minimal container and install only our build deps; mock does
    # not work in an unprivileged container (no CAP_SYS_ADMIN for mount), and
    # dnf --installroot is too broken (rhbz#1885103, #1885101, #1738233)
    container:
      image: docker.io/fedora:rawhide
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # otherwise we are testing target branch instead of the PR branch (see pull_request_target trigger)
          ref: ${{ github.event.pull_request.head.sha }}

      - name: install build dependencies
        run: |
          dnf install -y /usr/bin/xargs
          scripts/testing/dependency_solver.py -b | xargs -d '\n' dnf install -y --setopt=install_weak_deps=False --nodocs rpm-build

      - name: build RPMs
        run: |
          ./autogen.sh
          ./configure
          make rpms

      - name: run RPM tests
        run: |
          make run-rpm-tests-only || { cat tests/rpm_tests.log; exit 1; }

      - name: test installability
        run: |
          dnf install -y result/build/01-rpm-build/*.rpm
